### ISSUE TITLE
Ignore list

### ISSUE THREAD

**Issue by alepop** [alepop/yet-another-lisk-pool#2]
Add a field to `config.json` file with the ignored list of addresses, which will be excluded from payouts.
- [ ] Add field
- [ ] Update payout functionality

**Comment by gargamyle** [comment]
Please add option to set a weight cap for voters as well in config.json

**Comment by gargamyle** [comment]
Appears as though you have implemented weight cap as a weight ignore. While a weight ignore function still may be useful it would also be nice to have a cap function. For example, accounts > 50,000 get reward weight capped at 50,000 and accounts > 100,000 get ignored and no reward.
